---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: app
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  type: ClusterIP
  ports:
    - name: http
      port: 9187
      targetPort: 9187
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: app
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_SOURCE_NAME
              value: postgresql://app:app@postgres:5432/appdb?sslmode=disable
          ports:
            - containerPort: 9187
              name: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
