---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: app
  labels:
    app: grafana
    grafana_datasource: "1"
  annotations:
    grafana_datasource: "true"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
