---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: app
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['backend:8000']
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter:9187']
