---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: app
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: metrics
      port: 9600
      targetPort: 9600
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: app
  labels:
    app: opensearch
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9600
              name: metrics
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: data
          emptyDir: {}
