---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-local:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://app:app@postgres:5432/appdb
            - name: OPENSEARCH_ENABLED
              value: "true"
            - name: OPENSEARCH_HOST
              value: opensearch
            - name: OPENSEARCH_PORT
              value: "9200"
            - name: OPENSEARCH_SCHEME
              value: http
            - name: OPENSEARCH_USER
              value: ""
            - name: OPENSEARCH_PASSWORD
              value: ""
            - name: OPENSEARCH_INDEX
              value: logs-app-v1
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /items?limit=1
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
